accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns=[
    path('signup/',views.SignUpView.as_view(),name='signup'),
]

blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns=[

    path('',views.BlogPostListView.as_view(),name='home'),

    #/post/1/
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),

    #/post/new/
    path('post/new/',views.PostCreateView.as_view(),name='post_new'),

    #/post/1/edit/
    path('post/<int:pk>/edit/',views.PostUpdateView.as_view(),name='post_edit'),

    #/post/1/delete/
    path('post/<int:pk>/delete/',views.PostDeleteView.as_view(),name='post_delete'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')), # default authentication url
    path('accounts/',include('accounts.urls')), # custom url
    path('',include('blog.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=200)
    author=models.ForeignKey('auth.User',on_delete='models.CASCADE',) # many posts can have same author
    body=models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',args=[str(self.id)])

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

# Create your views here.
class SignUpView(CreateView):
    form_class=UserCreationForm
    success_url=reverse_lazy('login') # after successful submission of signup form it will redirect to login page.
    template_name='sign_up.html'

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from .models import Post
from django.urls import reverse_lazy

# Create your views here.
class BlogPostListView(ListView):
    model=Post
    template_name='home.html'

class PostDetailView(DetailView):
    model=Post
    template_name='post_detail.html'

class PostCreateView(CreateView):
    model=Post
    template_name='post_new.html'
    fields='__all__' # all fields will be shown in new form

class PostUpdateView(UpdateView):
    model=Post
    template_name='post_edit.html'
    fields=['title','body']

class PostDeleteView(DeleteView):
    model=Post
    template_name='post_delete.html'
    # Instead of using reverse here we use reverse_lazy because we only want to redirect the user to home page
    # only after successfull deletion of post. 
    success_url=reverse_lazy('blog:home') # it will redirect you to the home page after successful deletion.

templates/base.html
{% load staticfiles %}
<html>
    <head>
      <title>Django blog</title>
      <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:stylesheet">
      <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>
    <body>
      <div class="container">
        <header>
          <div class="nav-left">
            <h1><a href="/">Django blog</a></h1>
          </div>
          <div class="nav-right">
            <a href="{% url 'blog:post_new' %}">+ New Blog Post</a>
          </div>
        </header>
        {% if user.is_authenticated %} <!-- user is the current user. we are checking whether user is authenticated or not-->
          <p>Hi {{user.username}}</p>
          <a href="{%url 'logout'%}">Logout</a> <!-- logout is django default url-->
        {% else %}
          <p>You are not logged in </p>
          <a href="{% url 'login' %}">Login</a> <!-- login is django default url-->
        {%endif%}
        {% block content %}
        {% endblock content%}
      </div>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}
{%block content%}
  {% for blog in object_list %}
    <div class='post-entry'>
      <h2><a href="{% url 'blog:post_detail' blog.pk %}">{{blog.title}}</a></h2>
      <p>{{blog.body}}</p>
    </div>
  {%endfor%}
{%endblock content%}

templates/post_delete.html
{% extends 'base.html' %}

{% block content%}
  <h1>Delete post</h1>
  <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ post.title }}"?</p>
    <input type="submit" value="Confirm" />
  </form>
{%endblock content%}

templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="post-entry">
    <h2>{{ post.title }}</h2> <!--post is the name of model or instead of post we can write object-->
    <p>{{ post.body }}</p>
  </div>
  <a href="{% url 'blog:post_edit' post.pk %}">+ Edit Blog Post</a></br>
  <a href="{% url 'blog:post_delete' post.pk %}">+ Delete Blog Post</a>
{% endblock content %}

templates/post_edit.html
{% extends 'base.html' %}

{% block content %}
  <h1>Edit post</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
  </form>
{% endblock %}

templates/post_new.html
{% extends 'base.html'%}

{% block content%}
  <h1>New Post</h1>
  <form action="" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit"value="Save"/>
  </form>
{% endblock content%}

templates/sign_up.html
{% extends 'base.html' %}

{% block content %}
<h1>Sign Up</h1>
<form method="post">
  {%csrf_token%}
  {{form.as_p}} <!--as_p means form is in the form ofparagraph-->
  <button type="submit">Sign Up</button>
</form>
{% endblock content %}